### ISSUE TITLE
Issue when bundling with rollup

### ISSUE THREAD

**Issue by schadenn** [ChALkeR/safer-buffer#7]
Hi,

when using rollup to bundle, it converts modules to something like this:
```
var bufferEs6 = /*#__PURE__*/Object.freeze({
  __proto__: null,
  Buffer: Buffer,
  INSPECT_MAX_BYTES: INSPECT_MAX_BYTES,
  SlowBuffer: SlowBuffer,
  isBuffer: isBuffer,
  kMaxLength: _kMaxLength
});
```

Because the Object is explicitly set to have no prototype, this check in safer-buffer will fail (no prototype -- no hasOwnProperty()):
`if (!buffer.hasOwnProperty(key)) continue`

If you use the following instead, it'll work fine:
`if (!Object.hasOwnProperty.call(buffer, key)) continue`

Do you think this solution would be safe enough to rewrite?

**Comment by davidpanic** [comment]
This is STILL an issue, also happens with the latest Deno (v1.6.2).

```ts
import { createRequire } from "https://deno.land/std@0.82.0/node/module.ts";

const require = createRequire(import.meta.url);
const Buffer = require('safer-buffer').Buffer;
```

throws the following:
```
Check file:///home/david/code/deno/bugtest/src/index.ts
error: Uncaught TypeError: buffer.hasOwnProperty is not a function
  if (!buffer.hasOwnProperty(key)) continue
              ^
    at Object.<anonymous> (file:///home/david/code/deno/bugtest/node_modules/safer-buffer/safer.js:13:15)
    at Module._compile (module.ts:161:36)
    at Object.Module._extensions..js (module.ts:1084:10)
    at Module.load (module.ts:140:34)
    at Function._load (module.ts:406:14)
    at Module.require (module.ts:126:21)
    at require (module.ts:1133:16)
    at index.ts:4:16
```

**Comment by sibelius** [comment]
would u accept a pull request to fix this?

**Comment by chisNaN** [comment]
Hello. Thanks for all

I came across this topic because i have been developing a web app with snowpack version 3.8.2
but i cope with the same error when using ipfs-http-client lib (relying on safer-buffer i guess)
actually the project will manage to build BUT NOT to start
i would like to have another workaround to uncomment my ipfs code when i build and deploy(((

Thanks in advance
